kind: Pod
apiVersion: v1
metadata:
  name: mysql-client
  labels:
    name: mysql-client
spec:
  containers:
    - name: mysql-client
      image: akalashnykov/mysql-client:1.0
      command: ["sleep", "1000"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "64Mi"
          cpu: "500m"
